name: mycard
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/myPic.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Charm
      fonts:
        - asset: fonts/Charm-Regular.ttf
        - asset: fonts/Charm-Bold.ttf
          weight: 700
    - family: Muli
      fonts:
        - asset: fonts/Muli-Italic-VariableFont_wght.ttf
        - asset: fonts/Muli-VariableFont_wght.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
